import 'package:flutter/material.dart';
import 'package:html/parser.dart' as parser;
import '../services/auth_service.dart';
import '../services/net_client.dart';
import '../services/site_config.dart';
import '../utils/forum_text.dart';
import 'native_chat_page.dart';

class NativeMessageListPage extends StatefulWidget{const NativeMessageListPage({super.key});@override State<NativeMessageListPage> createState()=>_NativeMessageListPageState();}
class _NativeMessageListPageState extends State<NativeMessageListPage>{
 List<_Pm> items=[];bool loading=true;String? error;
 @override void initState(){super.initState();load();}
 String clean(String s)=>forumText(s.replaceAll(RegExp(r'\s+'),' ').trim());
 Future<void> load()async{if(mounted)setState(()=>loading=true);try{await AuthService.instance.init();final c=await NetClient.instance.client;final cookie=AuthService.instance.authCookie??'';final u=Uri.parse('${SiteConfig.base}home.php').replace(queryParameters:{'mod':'space','do':'pm','mobile':'2','_t':'${DateTime.now().millisecondsSinceEpoch}'});final r=await c.get(u,headers:{'User-Agent':NetClient.ua,if(cookie.isNotEmpty)'Cookie':cookie}).timeout(const Duration(seconds:20));if(r.statusCode!=200)throw Exception('请求失败 HTTP ${r.statusCode}');final d=parser.parse(NetClient.decode(r.bodyBytes));for(final n in d.querySelectorAll('script,style,noscript,template'))n.remove();final out=< _Pm>[];final seen=<int>{};for(final a in d.querySelectorAll('a[href]')){final h=(a.attributes['href']??'').trim();final uid=getUid(h);if(uid<=0||uid==AuthService.instance.uid||!isConv(h)||seen.contains(uid))continue;final name=clean(a.text);if(name.isEmpty||generic(name))continue;dynamic n=a;for(var i=0;i<5&&n.parent!=null;i++){final p=n.parent,t=text(p);if(t.length>=name.length&&t.length<500)n=p;else break;}var preview=text(n);preview=remove(preview,name);final time=text(n.querySelector('time,.xg1,.xg2,[class*="time"],[class*="date"]'));if(time.isNotEmpty)preview=remove(preview,time);preview=preview.replaceAll(RegExp(r'^(私人消息|站内私信|私信|消息)\s*'),'').trim();if(preview.isEmpty||generic(preview))continue;seen.add(uid);out.add(_Pm(uid,name,preview,time));}if(mounted)setState(()=>{items=out;loading=false;error=null;});}catch(e){if(mounted)setState(()=>{error=clean(e.toString().replaceFirst('Exception: ',''));loading=false;});}}
 static bool isConv(String h){final x=h.toLowerCase();return(x.contains('do=pm')||x.contains('ac=pm'))&&(x.contains('touid=')||x.contains('pmid=')||x.contains('subop=view'));}
 static int getUid(String h){for(final k in const['touid','uid']){final m=RegExp('[?&]$k=(\\d+)').firstMatch(h);final v=int.tryParse(m?.group(1)??'');if(v!=null&&v>0)return v;}return 0;}
 static bool generic(String s)=>RegExp(r'^(站内私信|私人消息|私信|消息|查看全部私人消息|发送短消息)$').hasMatch(s.trim());
 static String remove(String s,String v){final i=s.indexOf(v);return i<0?s:'${s.substring(0,i)}${s.substring(i+v.length)}'.trim();}
 static String text(dynamic n){if(n==null)return'';try{final c=n.clone(true);for(final e in c.querySelectorAll('i.iconfont,i.comiis-icon,.iconfont,svg,[class*="iconfont"],[class*="comiis-icon"]'))e.remove();return(c.text??'').replaceAll(RegExp(r'\s+'),' ').trim();}catch(_){return(n.text??'').trim();}}
 @override Widget build(BuildContext context){final s=Theme.of(context).colorScheme;return Scaffold(backgroundColor:const Color(0xfff4f4f4),appBar:AppBar(title:const Text('消息'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh)),IconButton(onPressed:(){},icon:const Icon(Icons.edit))]),body:Column(children:[Container(height:48,color:Colors.white,child:Row(children:[Expanded(child:Center(child:Column(mainAxisAlignment:MainAxisAlignment.end,children:[const Text('私人消息',style:TextStyle(fontSize:16,fontWeight:FontWeight.w600)),const SizedBox(height:8),Container(width:30,height:3,color:s.primary)]))),Expanded(child:Center(child:Text('公共消息',style:TextStyle(color:s.onSurfaceVariant,fontSize:16))))])),Expanded(child:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(error!,textAlign:TextAlign.center),const SizedBox(height:12),FilledButton(onPressed:load,child:const Text('重试'))])):items.isEmpty?const Center(child:Text('暂无私人消息')):RefreshIndicator(onRefresh:load,child:ListView.separated(itemCount:items.length,separatorBuilder:(_,__)=>const Divider(height:1,indent:92),itemBuilder:(_,i){final x=items[i];return ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:20,vertical:5),leading:CircleAvatar(radius:34,backgroundImage:NetworkImage('${SiteConfig.base}uc_server/avatar.php?uid=${x.uid}&size=small')),title:Text(x.name),subtitle:Text(x.preview,maxLines:1,overflow:TextOverflow.ellipsis),trailing:Text(x.time,style:const TextStyle(fontSize:11)),onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>NativeChatPage(uid:x.uid,username:x.name)));})))]) );}
}
class _Pm{final int uid;final String name,preview,time;const _Pm(this.uid,this.name,this.preview,this.time);}
