name: ycoo_forum
description: "源论坛(YcooForum)民间移动端 - 阅读侧。"
publish_to: 'none'

version: 2.0.7+111

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  html: ^0.15.4
  shared_preferences: ^2.3.3
  cronet_http: ^1.9.0
  webview_flutter: ^4.10.0
  file_picker: ^10.3.2
  charset: ^2.0.1
  url_launcher: ^6.3.2
  package_info_plus: ^8.3.0
  device_info_plus: ^10.1.2
  path_provider: ^2.1.4
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
